name: Modificación del Código de la Aplicación

on:
  pull_request:
    types: [labeled]

jobs:
  modificar_codigo:
    if: github.event.label.name == 'modificacion-codigo'
    runs-on: ubuntu-latest
    steps:
      - name: Revisar modificación de código
        run: |
          echo "Modificación de código solicitada en el PR: ${{ github.event.pull_request.title }}"
          echo "Descripción: ${{ github.event.pull_request.body }}"
