name: Solicitud de Nueva Funci贸n

on:
  issues:
    types: [labeled]

jobs:
  solicitud_funcion:
    if: github.event.label.name == 'nueva-funcion'
    runs-on: ubuntu-latest
    steps:
      - name: Revisar solicitud de nueva funci贸n
        run: |
          echo "Nueva funci贸n solicitada: ${{ github.event.issue.title }}"
          echo "Descripci贸n: ${{ github.event.issue.body }}"
